host=ldap://127.0.0.1
dn=cn=admin,dc=test,dc=local
password=XXXXXX
base=dc=test,dc=local
userbase=dc=test,dc=local
rdnattribute=uid
branchForEtd=ou=etd
branchForEsn=ou=esn
branchForAdm=ou=adm
branchForAss=ou=association
branchForFon=ou=bfonctionnelle
backendFor=etd,adm,esn,ass
branchAttr=departmentNumber
disabledAttribute=sogxdisableflag
disableValue=1
enableValue=0
additionnalObjectClass=sogxUser

