name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: copy sources
        run: |
          mkdir -p .debpkg/var/lib/sesame-daemon/backends-modules/openldap/etc
          mkdir -p .debpkg/var/lib/sesame-daemon/backends-modules/openldap/bin
          mkdir -p .debpkg/var/lib/sesame-daemon/backends-modules/openldap/lib
          cp src/bin/* .debpkg/var/lib/sesame-daemon/backends-modules/openldap/bin
          chmod 700 .debpkg/var/lib/sesame-daemon/backends-modules/openldap/bin/*
          cp src/lib/* .debpkg/var/lib/sesame-daemon/backends-modules/openldap/lib
          cp src/etc/config.conf.exemple .debpkg/var/lib/sesame-daemon/backends-modules/openldap/etc
          cp src/config.yml .debpkg/var/lib/sesame-daemon/backends-modules/openldap
          cp README.md .debpkg/var/lib/sesame-daemon/backends-modules/openldap
          cp install.sh .debpkg/var/lib/sesame-daemon/backends-modules/openldap
          cp update.sh .debpkg/var/lib/sesame-daemon/backends-modules/openldap
          chmod 700 .debpkg/var/lib/sesame-daemon/backends-modules/openldap/install.sh
          chmod 700 .debpkg/var/lib/sesame-daemon/backends-modules/openldap/update.sh
      - uses: jiro4989/build-deb-action@v3
        with:
           package: sesame-backend-openldap
           package_root: .debpkg
           maintainer: Libertech
           version: ${{ github.ref }} # refs/tags/v*.*.*
           arch: 'amd64'
           depends: 'python3, python3-ldap, python3-jinja2, sesame-daemon'
           desc: 'LDAP backend for sesame-daemon'
           homepage: 'https://github.com/Libertech-FR/sesame-backend-ldap'
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sesame*
          overwrite: true
          file_glob: true
